# Generated by Django 6.0.4 on 2026-05-30 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_product_location'),
        ('packing', '0002_packingorder_created_on'),
        ('sales', '0005_salesorderitem_reserved_from_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PackingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.PositiveIntegerField(default=0)),
                ('quantity_scanned', models.PositiveIntegerField(default=0)),
                ('packing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_to_pack', to='packing.packingorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorderitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('packing_order', 'sales_order_item'), name='unique_packing_item_per_order_item')],
            },
        ),
    ]
