# Generated by Django 6.0.4 on 2026-06-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_packingorderitem_product_name_and_more'),
        ('users', '0004_company_userprofile_active_company_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packing_orders', to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packingorderitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packing_order_items', to='users.company'),
            preserve_default=False,
        ),
    ]
