# Generated by Django 6.0.4 on 2026-06-11 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0005_packingorder_company_packingorderitem_company'),
        ('users', '0004_company_userprofile_active_company_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='users.company')),
                ('packing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='packing.packingorderitem')),
                ('packing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='packing.packingorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
