# Generated by Django 6.0.4 on 2026-06-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_packingscanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
