# Generated by Django 6.0.4 on 2026-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0007_packingorder_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
