# Generated by Django 6.0.4 on 2026-07-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0008_packingorder_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingorder',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
