# Generated by Django 6.0.4 on 2026-06-18 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_department_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('SALES', 'Sales'), ('WAREHOUSE', 'Warehouse'), ('PACKING', 'Packing'), ('IT', 'IT'), ('HR', 'HR'), ('FINANCE', 'Finance')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('department', 'company')},
            },
        ),
    ]
