# Generated by Django 6.0.4 on 2026-07-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0002_logger_content_type_logger_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loggers', to='contenttypes.contenttype'),
        ),
    ]
