# Generated by Django 6.0.4 on 2026-05-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('MAIN', 'Main Warehouse'), ('SHOP', 'Shop Warehouse')], default='SHOP', max_length=20),
        ),
    ]
