# Generated by Django 6.0.4 on 2026-06-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
        ('users', '0008_userprofile_assigned_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenterticketcomment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='helpcenter_ticket_comments', to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helpcentertickethistory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='helpcenter_ticket_history', to='users.company'),
            preserve_default=False,
        ),
    ]
