# Generated by Django 6.0.4 on 2026-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0002_helpcenterticketcomment_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcenterticketcomment',
            name='comment',
            field=models.CharField(),
        ),
    ]
