# Generated by Django 6.0.4 on 2026-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_reserved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
