# Generated by Django 6.0.4 on 2026-05-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_stock_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_reserved',
            new_name='reserved_quantity',
        ),
    ]
