# Generated by Django 6.0.4 on 2026-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home', 'Home & Kitchen'), ('toys', 'Toys & Games'), ('books', 'Books'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('food', 'Food & Grocery'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
