# Generated by Django 6.0.4 on 2026-06-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_category'),
        ('users', '0004_company_userprofile_active_company_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.company'),
            preserve_default=False,
        ),
    ]
