# Generated by Django 6.0.4 on 2026-06-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
