# Generated by Django 6.0.4 on 2026-06-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_transfer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
