# Generated by Django 6.0.4 on 2026-06-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_company'),
        ('transfers', '0003_transfer_notes'),
        ('users', '0004_company_userprofile_active_company_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='quantity',
        ),
        migrations.CreateModel(
            name='TransferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_products', to='users.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_products', to='transfers.transfer')),
            ],
        ),
        migrations.AddField(
            model_name='transfer',
            name='items',
            field=models.ManyToManyField(through='transfers.TransferProduct', to='inventory.product'),
        ),
    ]
