# Generated by Django 6.0.4 on 2026-05-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100)),
                ('carrier', models.CharField(choices=[('UPS', 'UPS'), ('FEDEX', 'FedEx'), ('DHL', 'DHL'), ('INPOST', 'InPost'), ('GLS', 'GLS'), ('POCZTA POLSKA', 'Poczta Polska'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('IN WAREHOUSE', 'In Warehouse'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
