# Generated by Django 6.0.4 on 2026-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
