# Generated by Django 6.0.4 on 2026-06-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_packingorderitem_product_name_and_more'),
        ('tracking', '0002_tracking_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='packed_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingorder'),
        ),
    ]
