# Generated by Django 6.0.4 on 2026-06-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_salesorder_status'),
        ('tracking', '0004_tracking_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='sales.salesorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN WAREHOUSE', 'In Warehouse'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], max_length=20),
        ),
    ]
