# Generated by Django 6.0.4 on 2026-05-13 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN WAREHOUSE', 'In Warehouse'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('ship_to', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STORE', 'Store')], default='STORE', max_length=20)),
                ('ship_address', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('payment_method', models.CharField(choices=[('ON DELIVERY', 'On Delivery'), ('AT STORE', 'At Store'), ('PAID', 'Paid'), ('PREPAID', 'Prepaid'), ('NET 7', 'Net 7'), ('NET 14', 'Net 14'), ('NET 30', 'Net 30')], default='AT STORE', max_length=20)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.tracking')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
