# Generated by Django 6.0.4 on 2026-05-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0002_salesorderitem_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='items',
            field=models.ManyToManyField(through='sales.SalesOrderItem', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
    ]
