# Generated by Django 6.0.4 on 2026-05-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_customer_id_customer_name'),
        ('sales', '0003_salesorder_items_alter_salesorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='ship_to',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'Customer'), ('STORE', 'Store')], default='STORE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('IN WAREHOUSE', 'In Warehouse'), ('PACKED', 'Packed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('PAID', 'Paid')], default='DRAFT', max_length=20, null=True),
        ),
    ]
