# Generated by Django 6.0.4 on 2026-05-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_salesorder_customer_alter_salesorder_ship_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='reserved_from_assigned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='reserved_from_main',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
