# Generated by Django 6.0.4 on 2026-06-04 07:08

import django.db.models.deletion
from django.db import migrations, models


def backfill_salesorderitem_product_snapshot(apps, schema_editor):
    SalesOrderItem = apps.get_model('sales', 'SalesOrderItem')

    for item in SalesOrderItem.objects.select_related('product').all().iterator():
        if not item.product_id or not item.product:
            continue

        updated_fields = []
        if not item.product_sku:
            item.product_sku = item.product.sku
            updated_fields.append('product_sku')
        if not item.product_name:
            item.product_name = item.product.name
            updated_fields.append('product_name')

        if updated_fields:
            item.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_product_location'),
        ('sales', '0005_salesorderitem_reserved_from_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product_sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
        migrations.RunPython(backfill_salesorderitem_product_snapshot, migrations.RunPython.noop),
    ]
