# Generated by Django 6.0.4 on 2026-06-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesorderitem_product_name_and_more'),
        ('users', '0004_company_userprofile_active_company_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='users.company'),
            preserve_default=False,
        ),
    ]
